### ISSUE TITLE
[Question] How to use Mercure for several domains?

### ISSUE THREAD

**Issue by Gamulator** [api-platform/api-platform#1220]
Hi.

We use API Platform in Symfony. It's a great tool. And we use Mercure to update client chats when Doctrine triggers an event like "new chat message registered". It works fine except one thing. 
We have 2 domains: myexample.com for desktop layout and m.myexample.com for mobile one. When some client sends a message in his chat, Mercure updates corresponding topic, but for this client's domain only. It uses an absolute URL when prepares to publish. So if a client opens the same chat in two browser tabs but under desktop and mobile domains, each of these chat copies works alone, not synchronously.
What is the right way to publish updates to both subscribers?

Thanks.

**Comment by byhoratiss** [comment]
I don't think Api-platform could manage that "natively".
But you could make your own publish mechanism, maybe:
* Doctrine subscriber that publishes each changed entity with/without absolute URL.
* Subscriber to kernel events to do the same.

If you use a full absolute URL like Api-platform you will reach the same problem, but if you change the topic to something more common like "product/123.jsonld" instead of "https://domain.com/product/123.jsonld" you could have multiple subscribers to that.
Hope I've explained myself correctly.

**Comment by Gamulator** [comment]
Thank you.

We solved it using topic mask. When a client subscribes to Mercure channels we set it's topic to http://{host}/api/chat/messages/{id}. It works as expected.
