### ISSUE TITLE
Empty Object transform to empty array

### ISSUE THREAD

**Issue by omnescorp** [api-platform/api-platform#1223]
FW: symfony 4.2

When trying to create an empty object the `api:swagger:export` transform empty objects into empty arrays.
I need that a specific resource doesn't use the swagger api_keys, instead, I want to use nothing as security.

Yaml:

```
...
consumes:
   - application/json
produces:
   - application/json
security: [ { } ]
```
Them I run `./bin/console api:swagger:export`

Actual:
```
"security": [
                    []
                ],
```
Expected:
```
"security": [
                    {

                    }
                ],
```

Thanks.

**Comment by dunglas** [comment]
Why do yo add an empty definition in your YAML? It's a known issue in PHP, empty "associative" arrays are serialized as JSON arrays. The only workaround is to use `\ArrayObject` instead of a raw array. Maybe could it be done by normalizing the config (https://symfony.com/doc/current/components/config/definition.html#normalization).

**Comment by teohhanhui** [comment]
See https://github.com/symfony/symfony/pull/28363

It will be in Symfony 4.4

**Comment by omnescorp** [comment]
Thanks, @teohhanhui, that is exactly what I mean.
