### ISSUE TITLE
502 bad gateway error when running project using docker-compose on MacOs

### ISSUE THREAD

**Issue by John-Moya** [api-platform/api-platform#1536]
![Captura de Pantalla 2020-05-24 a la(s) 18 59 49](https://user-images.githubusercontent.com/8208087/82769201-bf92c400-9df0-11ea-8e24-d03f859a2824.png)

Tried Rebuilding and stop run again

**Comment by s1k3s** [comment]
By default, the Docker setup of API Platform will run the following when started on the PHP container:
1. `composer install`
2. Query the database container until it's running
3. `bin/console doctrine:schema:update`

When starting for the first time, it's common for the composer command to take longer, since it doesn't have the dependencies cached locally and will attempt to download them.

I would suggest the following:

1. Run `docker-compose down` to stop all containers if they are running.
2. Run `docker-compose build`.
3. Run `docker-compose up` (without -d) and inspect the full output of this command. In case any container fails to start you should see the errors in your console.

If the errors are not clear you can post the full output of that command here and we can further check.

**Comment by John-Moya** [comment]
Hi @s1k3s I get the following db error 
```php_1      | Waiting for db to be ready...
php_1      |
php_1      |                     Application Migrations
php_1      |
php_1      |
php_1      | Migrating up to 20200513022718 from 20200513010245
php_1      |
php_1      |   ++ migrating 20200513022227
php_1      |
php_1      |      -> DROP SEQUENCE greeting_id_seq CASCADE
db_1       | 2020-05-25 22:40:44.455 UTC [29] ERROR:  sequence "greeting_id_seq" does not exist
db_1       | 2020-05-25 22:40:44.455 UTC [29] STATEMENT:  DROP SEQUENCE greeting_id_seq CASCADE
php_1      | Migration 20200513022227 failed during Execution. Error An exception occurred while executing 'DROP SEQUENCE greeting_id_seq CASCADE':
php_1      |
php_1      | SQLSTATE[42P01]: Undefined table: 7 ERROR:  sequence "greeting_id_seq" does not exist
php_1      |
php_1      | In AbstractPostgreSQLDriver.php line 63:
php_1      |
php_1      |   An exception occurred while executing 'DROP SEQUENCE greeting_id_seq CASCAD
php_1      |   E':
php_1      |
php_1      |   SQLSTATE[42P01]: Undefined table: 7 ERROR:  sequence "greeting_id_seq" does
php_1      |    not exist
php_1      |
php_1      |
php_1      | In PDOConnection.php line 83:
php_1      |
php_1      |   SQLSTATE[42P01]: Undefined table: 7 ERROR:  sequence "greeting_id_seq" does
php_1      |    not exist
php_1      |
php_1      |
php_1      | In PDOConnection.php line 78:
php_1      |
php_1      |   SQLSTATE[42P01]: Undefined table: 7 ERROR:  sequence "greeting_id_seq" does
php_1      |    not exist
php_1      |
php_1      |
php_1      | doctrine:migrations:migrate [--write-sql [WRITE-SQL]] [--dry-run] [--query-time] [--allow-no-migration] [--all-or-nothing [ALL-OR-NOTHING]] [--configuration [CONFIGURATION]] [--db-configuration [DB-CONFIGURATION]] [--db DB] [--em EM] [--shard SHARD] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command> [<version>]
```

**Comment by John-Moya** [comment]
@s1k3s How can I edit the config of the dabatase user and password?

**Comment by s1k3s** [comment]
You can find the DB container configuration in your `docker-compose.yml` file. Here it is on the repo: https://github.com/api-platform/api-platform/blob/ef0659e1532cdca3c1f186c2e162cb56ad7aa1d5/docker-compose.yml#L58

The Bad Gateway issue is caused by the SQL error you posted above. It looks like you have a migration file which tries to delete a non existing table.
