### ISSUE TITLE
Exception if entity id is invalid

### ISSUE THREAD

**Issue by djpremier** [api-platform/api-platform#1594]
**API Platform version(s) affected**: 2.5.5

**Description**  

When a POST request is made by passing the entity / iri with ID undefined an exception is raised, in the behavior that I believe to be correct this should be treated to the point of returning a 404. As you can see, this is because I use Uuid and then undefined is not a compatible partner.

`An exception occurred while executing 'SELECT u0_.id AS id_0, u0_.created_at AS created_at_1, ... u0_.owner_id AS owner_id_11 FROM unit_measurement u0_ WHERE (u0_.id = ? AND (u0_.owner_id = ? AND u0_.used_in IS NULL)) AND (u0_.deleted_at IS NULL)' with params ["undefined", "a82c0436-91b9-4641-8fa7-e161c784ff36"]:↵↵SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for type uuid: "undefined"`

**How to reproduce**  

> UnitMeasurement.php
```
class UnitMeasurement
{
    /**
     * @Assert\Uuid
     * @Groups({"base_entity_read"})
     * @ORM\Id()
     * @ORM\GeneratedValue(strategy="UUID")
     * @ORM\Column(type="guid", unique=true)
     */
    private $id;
}
```

> Product.php (Where I have the relationship)
```
class Product
{
    /**
     * Unit measurement entity
     * 
     * @Assert\Type(UnitMeasurement::class)
     * 
     * @var UnitMeasurement
     */
    public $unitMeasurement;
}
```

> Data sent
```
{
    unitMeasurement: "/api/unit_measurements/undefined"
}
```

> Correct data example
```
{
    unitMeasurement: "/api/unit_measurements/b92ad920-e1a4-47af-ac2e-4220c0bf50d5"
}
```

Regex to validade Uuid: `[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}`

**Possible Solution**  

**Additional Context**

**Comment by rugolinifr** [comment]
I do not use uuid, so perhaps what i'm goind to say is irrelevant.

Following the error message, i see that you're using a dbms with a dedicated uuid type (Postgre?) instead of a regular string. It seems you can't pass a malformed argument to your where clause without throwing an error.  I don't know if it is api-platform job to check the consistency of an argument according to the dbms implementation.

So i don't know... what happens if you change the column type to string ?

```
     * @Assert\Uuid
     * @Groups({"base_entity_read"})
     * @ORM\Id()
     * @ORM\GeneratedValue(strategy="UUID")
     * @ORM\Column(type="string", unique=true)
    private $id;
```

**Comment by djpremier** [comment]
Hello @rugolinifr, thanks for responding. This value is from Doctrine itself (https://www.doctrine-project.org/projects/doctrine-orm/en/2.7/reference/basic-mapping.html), it maps to string or if possible for a specific type.

As I listed another issue, this problem exists because the API is not being validated on the correct format, but it was already raised that it was not possible because the base library does not provide the test, I am not sure how it works, I am out of time on time to check implementations and be able to make corrections.

But currently I use this regex to check if the value passed is a Uuid.
Regex: `[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}`

**Comment by rugolinifr** [comment]
> it maps to string or if possible for a specific type.

Yes, that's what i meant. That's why i wondering what happen when you force doctrine to use its **string** type instead of **guid**. You can compare any dummy id against another string within the dbms. 

Curiosity purpose, may i know what is the lifecycle step (event) you're using the regex against the uuid ?

**Comment by soyuka** [comment]
IMO it's indeed a doctrine issue, using ramsey/uuid + ramsey/uuid-doctrine works well and is tested in this library. I agree with @rugolinifr that the doctrine type must be wrong.
