### ISSUE TITLE
Framework and doctrine-agnostic event system

### ISSUE THREAD

**Issue by CvekCoding** [api-platform/api-platform#1770]
**Description**  
Hello.
Didnt you think about your own framework-agnostic event system? For example throw events on every CRUD operation on every entity.

This way we can be closer to domain-events concept. WDYT?

**Comment by dunglas** [comment]
We had one on v1, we removed it in V2A because it's not necessary anymore. Using decorators and existing extension points is enough for all use cases: https://api-platform.com/docs/core/extending/

We'll not change that anytime soon, but creating an external bundle adding a custom event system for developers wanting something more high level could be nice!

**Comment by alanpoulain** [comment]
There is a bundle adding events for the GraphQL part: https://github.com/alanpoulain/ApiPlatformEventsBundle.
