### ISSUE TITLE
(v3.0) Custom operations with custom State Providers are not working well

### ISSUE THREAD

**Issue by Raphy** [api-platform/api-platform#2312]
**API Platform version(s) affected**: 3.0

**Description**  
I've 2 entities (`User` and `Profile`) with custom operations for each of them:
```php
#[
   // ...
    ApiResource,
    Get,
    Post(
        uriTemplate: '/users/{id}/{transitionName}.{_format}',
        uriVariables: ['id', 'transitionName'],
        controller: UserMeWorkflowTransitionController::class,
    ),
    Get(
        uriTemplate: '/users/me.{_format}',
        shortName: 'UserMe',
        security: 'is_fully_authenticated()',
        provider: UserMeState::class,
    ),
    Post(
        uriTemplate: '/users/me/{transitionName}.{_format}',
        uriVariables: ['transitionName'],
        controller: UserMeWorkflowTransitionController::class,
        shortName: 'UserMe',
        security: 'is_fully_authenticated()',
        provider: UserMeState::class,
        itemUriTemplate: '/users/me.{_format}',
    ),
    // ...
]
class User //...
```

```php
#[
    // ...
    ApiResource,
    Get,
    Put,
    Get(
        uriTemplate: '/profiles/me.{_format}',
        shortName: 'ProfileMe',
        security: 'is_fully_authenticated()',
        provider: ProfileMeState::class,
    ),
    Put(
        uriTemplate: '/profiles/me.{_format}',
        shortName: 'ProfileMe',
        security: 'is_fully_authenticated()',
        provider: ProfileMeState::class,
    ),
]
class Profile // ...
```

And here the providers:

```php
<?php

namespace App\State;

use ApiPlatform\Metadata\Operation;
use ApiPlatform\State\ProviderInterface;
use App\Entity\User;
use Symfony\Component\Security\Core\Security;

class UserMeState implements ProviderInterface
{
    public function __construct(
        private readonly Security $security,
    ) {
    }

    public function provide(Operation $operation, array $uriVariables = [], array $context = []): object|array|null
    {
        if (User::class !== $operation->getClass()) {
            return null;
        }

        $user = $this->security->getUser();
        if (!$user instanceof User) {
            return null;
        }

        return $user;
    }
}
```

```php
<?php

namespace App\State;

use ApiPlatform\Metadata\Operation;
use ApiPlatform\State\ProviderInterface;
use App\Entity\Profile;
use App\Entity\User;
use Symfony\Component\Security\Core\Security;

class ProfileMeState implements ProviderInterface
{
    public function __construct(
        private readonly Security $security,
    ) {
    }

    public function provide(Operation $operation, array $uriVariables = [], array $context = []): object|array|null
    {
        if (Profile::class !== $operation->getClass()) {
            return null;
        }

        $user = $this->security->getUser();
        if (!$user instanceof User) {
            return null;
        }

        return $user->profile;
    }
}
```

1. When I send `GET /users/me` it works properly and the `UserMeState::provide` is called
2. When I send `GET /profiles/me` it works properly and the `ProfileMeState::provide` is called
3. When I send `POST /users/me/a_transition` it works as I want, the `UserMeState::provide` is called, but it should not according the API Platform code (I will explain after why)
4. When I send `POST /users/an_uuid/a_transition` it doesn't work, I've an error `[Semantical Error] line 0, col 40 near 'transitionName': Error: Class App\\Entity\\User has no field or association named transitionName`. The `transitionName` variable is not an entity field and it's only used in the controller.
5. When I send `PUT /profiles/me` the weirdest occurs: the request works but the `ProfileMeState::provide` is not called so a new entry in the database is created

After debugging why all of these scenario work or don't work, I've found some incoherences: 

- For my 3rd scenario, in the file [UriTemplateResourceMetadataCollectionFactory.php#150](https://github.com/api-platform/core/tree/main/src/Metadata/Resource/Factory/UriTemplateResourceMetadataCollectionFactory.php#L150), the count comparison is not logical because it seems to expect to have the `id` variable but as I've only `transitionName` variable, the counts are equal and then in the file [ReadListener#88](https://github.com/api-platform/core/tree/main/src/Symfony/EventListener/ReadListener.php#L88) it have only 1 variables, the `id` variable. That's also why in [ReadListener#63](https://github.com/api-platform/core/tree/main/src/Symfony/EventListener/ReadListener.php#L63) the listener don't stop and will call the state provider, the `$operation->getUriVariables()` contains 1 variable.

- For my 5th scenario, because the explaination of  the 3rd scenario, it doesn't work, the state provider is not called because there is no variables and the `ReadListener` stops at [ReadListener#63](https://github.com/api-platform/core/tree/main/src/Symfony/EventListener/ReadListener.php#L63).

I don't know how to solve these issues or if I'm doing wrong something.

**How to reproduce**  
Create the same custom operations with custom state providers.

**Possible Solution**  
I don't have a solution yet and I'm blocked.

**Comment by JeremyPasco** [comment]
I'm not sure what you means by "When I send PUT /profiles/me the weirdest occurs: the request works but the ProfileMeState::provide is not called so a new entry in the database is created".

State Providers will only provide a way to customize answers to your requests (normalization phase). If you want to customize the denormalization phase, you should use a State Processor.

By the way, you've got 2 PUT endpoints for your Profiles resource. The first one uses the default `uriTemplate: '/profiles/{uuid}.{_format}',`.
I wonder if your attempt to reach your second PUT endpoint doesn't fall into this first one. In this case `me` would be used as uuid. 

I understand that some GET /me endpoint could be useful in a stateless application. But since you can easily fetch your own profile or user URI this way, why not use it to edit your user/profile then?
1) Client send GET request to /user/me
2) Client extract '@id' field from response as uri
3) Client send PUT request to this uri with payload

**Comment by Raphy** [comment]
The wanted behavior is when I send `PUT /profiles/me`, I want to get the `$security->getUser()->getProfile()` by a State Provider. Since it's an entity, the Doctrine State Processor will be fine to persist. But in my case and with my configuration, my State Provider is not called and a new resource is created (like a POST) and persisted.

I've configured the 2 PUT endpoints to validate the parameter "id" is a valid UUID. I don't have issue with the endpoint called so `me` is not considered as an UUID.

I would to customize these endpoint because I don't want to expose the authenticated user id and its profile id. Regardless, It's a wanted behavior I already could set up with API Platform v2 :(

**Comment by itorgov** [comment]
Hi there! The API Platform version 2.7 is also affected. I faced with the same issue in one of my projects I'm working on.

**Comment by soyuka** [comment]
Hi please give me a reproducer. I think that having a provider **and** a controller is wrong. Pick one or the other, using a controller you bypass everything in API Platform just as you're doing a Symfony Route. We have many many test cases on api-platform/core that use custom providers/processors without problems.

**Comment by soyuka** [comment]
On 3.2 it's not the case anymore. It'll still be possible to use listeners but we won't recommend it as it leads to sometimes unwanted behaviors and hard-to-debug cases. In my personal opinion, it'd be better to be able to compose with providers/processors within a controller (something like middlewares with laravel).

**Comment by AhmedMasbah** [comment]
I want example  State Providers  (v3.0)

**Comment by VictorKrasnov** [comment]
I have the same issue. I have /users CRUD for admin panel.  And I want to make /profile route for operations with user profile for simple autentificated user. Okay, I can write custom logic with a state processor. But this is not simple project, I write reusable bundle. I don't know exactly which fields user entity may contain. In my processor I have just new entity with some null values, and some filled values in PATCH operation. But null doesn't means, that this value is unchangeable for authorised user, he can erase some data for example. I also can't normalize $data with known normalizationContext, because of error: Unable to generate an IRI for the item of type \"App\\Entity\\User\\User\...
How to PATCH some object in that case, can anybody show me an example?

**Comment by VictorKrasnov** [comment]
I did it and it works, but in my opinion it's a bad solution:
```php
    /**
     * @throws ExceptionInterface
     * @throws ReflectionException
     */
    public function process(mixed $data, Operation $operation, array $uriVariables = [], array $context = [])
    {
        if ($operation instanceof DeleteOperationInterface) {
            return $this->removeProcessor->process($data, $operation, $uriVariables, $context);
        } elseif ($operation instanceof Patch) {
            /** @var UserInterface $currentUser */
            $currentUser = $this->tokenStorage->getToken()->getUser();
            if (!$currentUser instanceof UserInterface || !$data instanceof UserInterface) {
                return null;
            }
            $reflectionData = new ReflectionClass($data);
            $reflectionData->getProperty('id')->setValue($data, $currentUser->getId());
            $data = $this->serializer->normalize($data, null, $operation->getDenormalizationContext());
            unset($data['id']);
            $reflectionCurrentUser = new ReflectionClass($currentUser);
            foreach ($data as $key => $value) {
                if ($reflectionCurrentUser->hasProperty($key)) {
                    $reflectionCurrentUser->getProperty($key)->setValue($currentUser, $value);
                }
            }
            return $this->persistProcessor->process($currentUser, $operation, $uriVariables, $context);
        }
        return null;
    }
```

**Comment by VictorKrasnov** [comment]
#[UniqueEntity] doesn't work correctly with the same processor (because $data expected as new instance of entity)... (((((

**Comment by Bguignard** [comment]
> > I think that having a provider **and** a controller is wrong. Pick one or the other, using a controller you bypass everything in API Platform just as you're doing a Symfony Route. We have many many test cases on api-platform/core that use custom providers/processors without problems.
> 
> Why would that be wrong? It seems like ReadListener is always called (unless you disable it) thus it's calling the in-built provider or your own custom provider to pass the object to your custom controller.

The problem is that the entity it provides you is based on given /id and thus, it gives to the PUT processor the object from the databases, not the one you gave with updated content. Then it will always refresh then entity with the entity from the database = no refresh. In my case I declare #[ApiResource] in DTO and its a pain since the documentation is really bad on providing custom POST, PUT and DELETE on DTOs (that are not directly Doctrine entities).

**Comment by jkabat** [comment]
Upgrading to v3+ is a mess. I cannot rewrite data transformers easily for DTO usage. I cannot use custom POST operations, because when read listener doesnt find an entity, Im always provided with the new one, so no 404 anymore. Security is called somewhat strangely - I never receive 404, but 403... 
It just needs too many workarounds to adapt daily base routines. Maybe it provides best practices, but that is relative IMHO...
