### ISSUE TITLE
Reliable way to use DTOs in v3?

### ISSUE THREAD

**Issue by 4rthem** [api-platform/api-platform#2483]
Hi,
Since Data Transformers were removed, I cannot find a way to use DTO with **nested** transformation: only the root item will use the Provider, not its sub-resources.

Also, DTO resulting from provider is passed to security instead of the resource object (https://github.com/api-platform/api-platform/issues/2466)

Am I missing something or am I the only one to use DTOs? ^^

Thanks for maintaining this project!

**Comment by 4rthem** [comment]
I believe output DTOs should only reside in the serialization process whereas Provider's role is to provide resource object (not the DTO) from (any) storage.
Would it be a good idea to reintroduce Data Transformers in the serialization process or something named `OutputDtoTransformer`?

**Comment by BenoitNorrin** [comment]
Hi,

I had a similar problem with nested DTOs and I sorted it out by removing the `output:` attribute on the Get operation defintion.

```php
#[ApiResource(operations: [
    new Get(
        formats: ['json'],
        security: "is_granted('ROLE_ADMIN')",
        #output: ClientOutput::class, <--- I commented that
        provider: ClientProvider::class,
    )
])]
class Client
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(targetEntity: self::class, inversedBy: 'filiales')]
    #[ApiProperty(readableLink: true)]
    private ?self $holding = null;

    #[MaxDepth(1)]
    #[ORM\OneToMany(mappedBy: 'holding', targetEntity: self::class)]
    private Collection $filiales;

    // ...
}
```


But yes I agree with you, everything become way more complicated the minute we start using DTOs ...

**Comment by BenoitNorrin** [comment]
Hi,

I agree with you @4rthem, everything become more complicated the minute we use DTOs ...

I'm having hard time with item denormalization. Here a quick exemple on how I'm using DTO's : https://gist.github.com/BenoitNorrin/8ab87eaed36bb32f57d5d6dcd7a23459

`BookPostInput` Dto have a `Author $author` propertie so when I post datas on `/api/books` (for example: `{"title": "my title", "author": "/api/authors/1"}`) the denormalization proccess returns a `BookOutput` Dto (because of [IrIConverter](https://github.com/api-platform/core/blob/24133dfecb584e50e26503d852c654fe2224e45d/src/Symfony/Routing/IriConverter.php#L95)) instead of a `Author` object. Is that normal ?

I found a workaround but I don't feel that's fine ...
When providers are called, the following context keys `operation` and `operation_name` seem removed. 

```php
if(false === array_key_exists('operation_name', $context)) {
    if ($operation instanceof CollectionOperationInterface) {
        return $this->collectionProvider->provide($operation, $uriVariables, $context);
    }
    return $this->itemProvider->provide($operation, $uriVariables, $context);
} else {
    // provide and return as a dto output...
}
```
Feel free to comment and improve.

**Comment by Renrhaf** [comment]
@BenoitNorrin maybe you commented the output because of the error described in https://github.com/api-platform/core/issues/5245 ? I have the same issue

**Comment by soyuka** [comment]
Not sure I get all the issues around that, just return whatever you want from your provider and it'll work, if you want automatic documentation use the `output` so that the Schema is correct in openapi. Also, there's a discussion space now which would probably be a better place for that.
