### ISSUE TITLE
add access token on swagger UI

### ISSUE THREAD

**Issue by angelzeke** [api-platform/api-platform#286]
Hi everybody,
I need your help to implement access token on swagger ui.
If someone has the same need I would be delighted to contribute with him

![oauthbooks](https://cloud.githubusercontent.com/assets/179226/25172114/506b02da-24f0-11e7-927f-ca142a54e269.PNG)

If someone has a track to be able to start it would help me a lot

I found this patch  https://github.com/api-platform/docs/issues/180 but it seems more news

**Comment by dunglas** [comment]
You can use the 2.1-dev version, it has built-in support for this feature: https://github.com/api-platform/core/pull/982

**Comment by benfavre** [comment]
Not sure how you expect people to set the name of the Header to "Authorization" or how to prepend "Bearer " to the token string.
Have tried everything, not sure what you mean by 2.1-dev has this "built-in", not sure this is possible right now, wich makes me wonder if this project is actually used by anyone ?

<img width="411" alt="screenshot_20170628_151538" src="https://user-images.githubusercontent.com/664679/27638817-b6e7b41c-5c14-11e7-9594-ca0f08e81750.png">

**Comment by meyerbaptiste** [comment]
You can find an example here: https://github.com/api-platform/docs/blob/ed356c95669307202e43aa5099a44fef0c0ac2a0/core/oauth2.md#oauth2-configuration

Doc PR isn't merged yet: https://github.com/api-platform/docs/pull/182

**Comment by benfavre** [comment]
Well after going through the process of changing how my whole project works in order to use the Oauth server. ("I didn't need to have" an Oauth server, just needed to validate tokens).
Basically for swagger to populate the token name the response from the API fetching the Auth params, needs to respond with this shape of response : 

```
{
access_token: "theToken",
token_type: "Bearer"
....
}
```

Anyway, there's still an issue in the procedure in the linked tutorial above, unless you set the default string of "bearer" is set to "Bearer" (capital B), then it fails.
So you need to add a config param (/app/config/config.yml): 

```
fos_oauth_server:
    service:
        options:
            token_type: Bearer
```

**Comment by younus-md** [comment]
@benfavre , Can you provide the sample project structure?

**Comment by Simperfit** [comment]
A doc PR is now present, please comment directly in it.
