### ISSUE TITLE
[QUESTION] Custom Extension+Symfony repositories 

### ISSUE THREAD

**Issue by MarsArt** [api-platform/api-platform#293]
In the api-platform, Custom Extension is used to modify the selection parameters. But how can I use the standard Symfony repositories? They return data instead of QueryBuilder.

**Comment by soyuka** [comment]
I think you should use filters instead of an extension.

Anyway, there are two kinds of extensions:

- Extension, returns a QueryBuilder see [QueryItemExtensionInterface](https://github.com/api-platform/core/blob/master/src/Bridge/Doctrine/Orm/Extension/QueryItemExtensionInterface.php) and [QueryCollectionExtensionInterface](https://github.com/api-platform/core/blob/master/src/Bridge/Doctrine/Orm/Extension/QueryCollectionExtensionInterface.php)
- ResultExtension, returns data (useful for pagination for example, or when you need to use `getQuery`, for `QueryHints` for example) see [QueryCollectionExtensionInterface](https://github.com/api-platform/core/blob/master/src/Bridge/Doctrine/Orm/Extension/QueryCollectionExtensionInterface.php) and [QueryResultItemExtensionInterface](https://github.com/api-platform/core/blob/master/src/Bridge/Doctrine/Orm/Extension/QueryResultItemExtensionInterface.php)

**Comment by Simperfit** [comment]
@MarsArt does soyuka's answer  is ok for you ?

**Comment by Simperfit** [comment]
@MarsArt If you still have an issue please feel free to post a comment so we can reopen the issue
