### ISSUE TITLE
Add extra information to the output

### ISSUE THREAD

**Issue by lvillarino** [api-platform/api-platform#340]
Hi:

I want to know how I can add extra information to the response, example

Original response
```
{
  "_links": {
    "self": {
      "href": "/item/8"
    }
  },
  "name": "hello",
  "id": 8
}
```

New Response

```
{
  "_links": {
    "self": {
      "href": "/item/8"
    }
  },
  "name": "hello",
  "id": 8,
  "_extra":{
    "api_version": "1.1.1",
    "timestamp": "342234324"
}
}
```

Thanks

**Comment by dunglas** [comment]
Use a service decorator (https://symfony.com/doc/current/service_container/service_decoration.html) to decorate the HAL item normalizer.

We really need to add a doc entry about that.

**Comment by lvillarino** [comment]
Do you have an example?

**Comment by synchr0n123r** [comment]
Please if any example. I'm looking exact same solutions as well.
Can't find it anywhere documentation

**Comment by synchr0n123r** [comment]
i found this: https://stovepipe.systems/post/service-decoration-in-practice

**Comment by silverbackdan** [comment]
Docs do have this info (perhaps not when this was originally raised though) For anyone finding this thread: https://api-platform.com/docs/core/serialization/#decorating-a-serializer-and-add-extra-data

**Comment by larzuk91** [comment]
Hi, I know this issue is already closed but I have a situation where decorating the HAL normalizer is not good enough. What I need is to add extra data to the output but to **all** formats. If I decorate the HAL normalizer it will apply only to `json+hal` requests.
The only solution I can see is to decorate all normalizers but I think that's just too much to do.

Is there any other approach I can take? 
Thanks!

**Comment by dunglas** [comment]
Decorate the Serializer class (which implements the NormalizerInterface and is actually the main normalizer).

**Comment by vnivuahc** [comment]
Hi @larzuk91
I had exactly the same issue. I could not get json+ld serialization + custom field work together.
That was because I modified the `supportsNormalization()` method to filter on which class apply my decoration.

Ex :

```php
    public function supportsNormalization($data, $format = null): bool
    {
        return $data instanceof MyClass;
    }
```

instead of :

```php
    public function supportsNormalization($data, $format = null): bool
    {
        return $this->decorated->supportsNormalization($data, $format);
    }
```

This breaks the normalization process. The normalizer stops and does not apply json+ld format (if the class is not a `MyClass` instance).
Then the json format is used as fallback instead od json+ld.

To get it work properly, I had to move my instance verification in the `normalize()` method :

```php
 public function normalize($object, $format = null, array $context = [])
    {
        $data = $this->decorated->normalize($object, $format, $context);
        if (!is_array($data)) {
            return $data;
        }

        if (!$object instanceof MyClass) {
            return $data;
        }

      // Add my custom field since the subject is a MyClass instance
}
```

**Comment by larzuk91** [comment]
Hey @vnivuahc 
Thanks for your example but I think there is a gotcha on it, the `json+ld` fields will be added to all kind of requests now (json, json+hal), isn't it? Anyway, I found a video where Ryan explains what's going on and how to overcome this situation. I'll leave you here the link in case you are interested: https://symfonycasts.com/screencast/api-platform-security/normalizer-aware#play

**Comment by vnivuahc** [comment]
Thank you very much for your link. It seems to be another approach.  
I'm not sure yet which are pros or cons with both approaches.

I don't think my code modifies anything for json/json+hal requests because I only decorate the json+ld normalizer :

```yaml
    #services.yaml
    App\Serializer\MyclassNormalizer:
        decorates: 'api_platform.jsonld.normalizer.item'
        decoration_priority: 43
        arguments: ['@App\Serializer\MyclassNormalizer.inner']
```

Well, this is a supposition, I only use json+ld so I could be wrong

**Comment by larzuk91** [comment]
Yeah, but you changed the `supportsNormalization` method. It will apply to all formats now
