### ISSUE TITLE
Install via Composer doesn't work

### ISSUE THREAD

**Issue by par4dise** [api-platform/api-platform#342]
Issue not related to the API itself, but to the **setup guide** provided on the [distribution page](https://api-platform.com/docs/distribution/), using Composer. 

After launching command `composer create-project api-platform/api-platform bookshop-api`:
* Download of dependencies is ok
* Settings parameters step by step is ok   
* Then a deprecation of some scripts happens: `ScriptHandler::buildBootstrap`, `ScriptHandler::clearCache`, `ScriptHandler::installAssets`, `ScriptHandler::installRequirementsFile`, etc. each one followed by warnings. 

Example of deprecation message:
> Deprecation Notice: The callback Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap declared at /path/www/api-platform/bookshop-api/vendor/sensio/distribution-bundle/Sensio/Bundle/DistributionBundle/Composer/ScriptHandler.php accepts a Composer\Script\CommandEvent but post-install-cmd events use a Composer\Script\Event instance. Please adjust your type hint accordingly, see https://getcomposer.org/doc/articles/scripts.md#event-classes in phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php:314   

Example of warning: 
> PHP Warning:  Module 'apcu' already loaded in Unknown on line 0

* Then the command `php bin/console doctrine:database:create` returns 
> Could not open input file: bin/console

Indeed there's no `console` file in bin. As I'm not a specialist of Symfony I did not try to go further.

**Comment by dunglas** [comment]
The warning (`PHP Warning: Module 'apcu' already loaded in Unknown on line 0`)  is due to your PHP install, not to API Platform (your probably have the same input when you type `php -v`). But it should not prevent the installation to work.

The deprecation notice is just a warning, not an error (it should not prevent to install the project). It has been fixed in API Platform 2.1 (actually in beta): `composer create-project api-platform/api-platform:^2.1@beta` to try it.

Before running `php bin/console doctrine:database:create`, did you changed to the newly created directory (`bookshop-api` in your case`)?

    cd bookshop-api
    php bin/console d:d:c

But why don't you use Docker instead? (just download the project and type `docker-compose up`).

**Comment by dunglas** [comment]
Can you tell me which PHP version do you use btw?

**Comment by par4dise** [comment]
Sure, sorry about that oversight:
> PHP 5.6.17 (cli) (built: Jan  8 2016 10:51:07) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies
    with Xdebug v2.2.5, Copyright (c) 2002-2014, by Derick Rethans

> Composer version 1.4.1 2017-03-10 09:29:45

I'm on macOS 10.12.5.

Answers:
* I've never had those warnings before. But I agree they're not errors.
* Yes I was in the correct directory
* Why not docker, well.... old habits :)
* I seems that the beta requires a newer PHP than mine:
> Could not find package api-platform/api-platform with version ^2.1@beta in a version installable using your PHP version 5.6.17

**Comment by Simperfit** [comment]
You are downloading the V1 of api-platform which contain `app/console` IIRC instead of `bin/console`. To use the V2 of api-platform you need PHP 7.0 or newer.

**Comment by par4dise** [comment]
Ok Simperfit that was that simple. Thank you.
