### ISSUE TITLE
ApiPlatform : custom order filter

### ISSUE THREAD

**Issue by achrafsmlali** [api-platform/api-platform#382]
I have an entity city and I created a function that calculates how far a user is from each city. I want to create a custom order filter that allows me to order these cities from the closest to the farthest.

Is it possible?

Thanks in advance for any guidance

**Comment by Simperfit** [comment]
Yes it's possible, you need to implement your own oder filter by following [this](https://api-platform.com/docs/core/filters#creating-custom-filters)

**Comment by achrafsmlali** [comment]
can you give me more details about how to do it in my case.
an example if it's possible apart the one in the doc

**Comment by Simperfit** [comment]
I don't know the code that you are running, I could just tell you to create that kind of custom filter and to use the code(based maybe on SQL) to update the queryBuilder like in the RegexpFilter.

**Comment by achrafsmlali** [comment]
if it was based on sql as you said it would be easy but it's not the case . i have a function with two parametres the first is user address (that i got from geolocalisation) and the secend is the city adress that i get from my table city. the aim now is to get all cities order by the result of my function. 
 @Simperfit

**Comment by yakobabada** [comment]
`<?php

declare(strict_types=1);

namespace App\Filter;

use ApiPlatform\Core\Bridge\Doctrine\Orm\Filter\OrderFilter;
use ApiPlatform\Core\Bridge\Doctrine\Orm\Util\QueryNameGeneratorInterface;
use Doctrine\ORM\QueryBuilder;

final class CustomOrderFilter extends OrderFilter
{
    protected function filterProperty(
        string $property,
        $direction,
        QueryBuilder $queryBuilder,
        QueryNameGeneratorInterface $queryNameGenerator,
        string $resourceClass,
        string $operationName = null
    ): void {
        // otherwise filter is applied to order and page as well
        if (!$this->isPropertyEnabled($property, $resourceClass)) {
            return;
        }

        $direction = strtoupper($direction);
        if (!\in_array($direction, ['ASC', 'DESC'], true)) {
            return;
        }

        $queryBuilder
            ->leftJoin(.......)
            ->groupBy(.......)
            ->orderBy(........., $direction);
    }

    public function getDescription(string $resourceClass): array
    {
        if (!$this->properties) {
            return [];
        }

        $description = [];
        foreach ($this->properties as $property => $strategy) {
            $description["$property"] = [
                'property' => $property,
                'type' => 'string',
                'required' => false,
                'swagger' => [
                    'name' => 'yourProperty',
                    'type' => 'string',
                ],
            ];
        }

        return $description;
    }
}`

And in your entity 


` * @ApiFilter(CustomOrderFilter::class, properties={"yourProperty"})`

**Comment by vincentchalamon** [comment]
@achrafsmlali I don't know if this issue is still active. Otherwise, I'm afraid filtering a query result by a PHP function is not the best solution, for performances reasons. Explaining...

To filter this collection through a PHP function will require to get the all results from your database first, and apply a usort (for example) based on your function. The original collection might be huge (France: ~35 000 cities).

A better way to handle this order would be to connect to the queryBuilder in a custom filter. Using PostgreSQL, I recommend you to have a look at [PostGIS](https://postgis.net/), and [jsor/doctrine-postgis](https://github.com/jsor/doctrine-postgis) for a Doctrine implementation of it.

Here is an example of a custom GeocodingFilter for API Platform, retrieving objects around a configured distance, using `ST_Distance_Sphere` operation: https://gist.github.com/vincentchalamon/6afb137e8c2d1dec1d5a1978b45b64ec. It could be easily adapted for your need to calculate each city distance from the user coordinates as a hidden field (cf. https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/reference/dql-doctrine-query-language.html), and order the queryBuilder by this field.

**Comment by vincentchalamon** [comment]
Closing in favor of solution explained in previous comment
