### ISSUE TITLE
FOSUserBundle, registration and confirmation email

### ISSUE THREAD

**Issue by piotaixr** [api-platform/api-platform#411]
I just configured FOSUserBundle and LexikJWTAuthenticationBundle in the Standard edition of api-platform.

I have a problem about user registration with this setup:
Enabling the FOSUser Bridge adds a step in the user resource handling using the userManager.

However, accounts created via a POST to /users are not activated by default.
Moreover, i didn't manage to find a way to send a confirmation email to the user with an activation token.
By looking into the FOSUserBundle controllers, they are using events to handle this case.

So, in order to use this feature, i started by adding an other EventListener that, when a user is successfully created, sends a confirmation email to the provided address by dispatching the FOSUserEvents::REGISTRATION_SUCCESS event that is then caught by FOSUB (sets the token, sends the email)

Then i thought: "Maybe i want to separate _registration_ and _account creation by admin_.
A custom collection operation and a small empty action are enough to be able to discriminate these two scenarios by route. 
This way, i can restrict access to the `user` resources and expose only the `register` custom operation to the public.

What do you think about this approach? Is there a better way of doing it?
Would it be interesting to refine the idea and add it to the FOSUB Bridge/document it on the docs repo?

**Comment by antoinemineau** [comment]
Account are not activated by default because the behaviour is that an admin has to enable it.
You can set a default value to the enabled property to change that.

About your approach I think it's the right one.

If you can look into this issue, it would help me a lot : https://github.com/FriendsOfSymfony/FOSUserBundle/issues/2605

You managed to install Api-platform with FOSUser and I didn't...

**Comment by soyuka** [comment]
https://github.com/api-platform/docs/pull/256 could maybe help you?

**Comment by antoinemineau** [comment]
You are my god.
Lost countless of hours just for one configuration line.

I was only missing this :
```
form: { enabled: true }
```
Documentation has always been so difficult to fine...

Thanks a lot.

**Comment by soyuka** [comment]
You have to thanks @piotaixr :).

**Comment by antoinemineau** [comment]
Thanks @piotaixr !
I have once again hope with my api-platform project but seriously not having this in the documentation or activated by default makes no sense to me.

**Comment by piotaixr** [comment]
@antoinemineau Didn't thought of this solution for enabling the user by default :D
But I actually need a valid address for the user so i need to activate the user using an email confirmation link.

After more testing it seems that the FOSUserBundle has some default behavior that cannot be customized so i will maybe need to rewrite the whole thing :s

**Comment by dunglas** [comment]
Seriously don't use FOSUser anymore. Creating custom users is so easy now (with http://symfony.com/doc/current/security/entity_provider.html and Guard) and extending FOSuser is so complex...

Writing a doc entry explaining how to create an auth system from A to Z is on my long todo list.

**Comment by dunglas** [comment]
See also https://github.com/api-platform/core/pull/1360

**Comment by antoinemineau** [comment]
Good feedback @dunglas.
I will look into those links, the right way might be to create our own authentication system and user management instead of finding a way to make FOSUser work with our requirements.

Thanks !

**Comment by Aerendir** [comment]
@Hounded, after all fosuserbundle doesn’t do much things: implementing resetting or confirmation or whatever else is all about a controller, a form and maybe a class for specific tasks...

I use fosuserbundle in an app without api platform, but I’m seriously considering to switch to a custom solution given the current simplicity in developing one...

**Comment by hounded** [comment]
@Arendir Do you have any links on where to start regarding resetting a password via api, it would be very much appreciated. Even some sudo code with the general idea would be great

**Comment by teohhanhui** [comment]
@dunglas May I suggest we deprecate the FOSUserBundle integration? It'll prevent more people from using it by default.

**Comment by Aerendir** [comment]
@hounded , I have no link because I never searched for this...

Anyway, you are put on the wrong way by the fact you are using api platform.

But registration, resetting, confirmation, ecc. are not task that pertain to api platform: the purpose of ApiPlatform is to manage resources (read: the entities you define in you application).

While registration, resetting, ecc. are operations you have to manage on yourself.

As a starting point you can read the code implemented by FOSUserBundle, and then reimplement it (in a more simple way) in your app.

The form part should be handled by your frontend (eg.: React).

For resetting the password, the flow is this:

1. `UserController::resetPassword()` receive the email via `POST`, from the form
2. If the email has a resetting code associated, returns a response that informs the frontend to show the form to insert the new password; if no code is already present, send it via email to the given email with a link to the `UserController::resetPassword()` action (route).
3. If the form is the one to submit the new password, then hash it and save. Maybe you require a new login or do the login automatically

This is a really simple flow.

On top of it, you can implement more features, like a check on the password strenghtness, a check on the expiration of the resetting code, automatic login after password change (or automatic logout - complete removal of cookies), ecc...

Anyway, start defining the actions you want your user to perform:

1. Registration
2. Password reset
3. Profile show

Then outline the fundamental steps and finally search for the way to implement them in Symfony...

**Comment by Aerendir** [comment]
@teohhanhui and @dunglas , maybe also explaining the reasons behind the decision.

The documentation says:

> Note: FOSUserBundle is not well suited for APIs. We strongly encourage you to use the Doctrine user provider shipped with Symfony or to create a custom user provider instead of using this bundle.

Maybe explaining the "why" will help users to better understand the drawbacks of using it in an ApiPlatform-based project...

And, maybe, also an article about how to do this should be of help!

**Comment by Warxcell** [comment]
@piotaixr can I ask how u enable ANONYMOUS access to post? 
I tried with:
```
@ApiResource(
 *     collectionOperations={
 *          "post"={
 *              "normalization_context"={"groups"={"post"}},
 *              "denormalization_context"={"groups"={"post"}},
 *              "validation_groups"={"Default", "registration"},
 *              "access_control"="is_granted('IS_AUTHENTICATED_ANONYMOUSLY')"
 *          }
 *      },
```

but it does not works for me? Thanks

**Comment by piotaixr** [comment]
@Warxcell Yup, that's the way I do it. Although, I configure my API using YAML.

Ex: That's the route I use for user registration (additional logic like send confirmation email, etc). I obviously want users to access it when not connected :-)

```yaml
resources:
    App\Entity\User:
        collectionOperations:
            register:
                method: POST
                route_name: user_register
                access_control: "is_granted('IS_AUTHENTICATED_ANONYMOUSLY')"
                denormalization_context:
                    groups:
                        - user-register
```
