### ISSUE TITLE
Coup de gueule

### ISSUE THREAD

**Issue by abysKri** [api-platform/api-platform#548]
Bonjour Duglas,
Cela fait plusieurs post de ma part concernant l'utilisation de ton bundle.
J'ai l'impression qu'il faille faire partie du club pour avoir une réponse, ou avoir des exemples.
J'ai meme pris  contact directement avec vos services et toujours rien.
Alors ma question, si je n'ai pas de réponse ici, et si je n'ai pas de réponse @les tilleuls.
Comment je fais pour pouvoir apprendre son fonctionnement ?
Merci

**Comment by GregoireHebert** [comment]
Bonjour @abysKri,

Navré que vous n'ayez pas trouvé parmi les réponses reçues les éléments qui vous permettraient d'avancer dans votre projet.
N'hésitez pas à aller regarder [la documentation](https://api-platform.com/docs) qui je l'espère, saura vous débloquer de la plupart des situations épineuses que vous recontrez.
Si toutefois vous êtes dans des cas d'utilisations très particuliers et/ou très avancés, n'hésitez pas à nous contacter dans le cadre d'une intervention de coaching / formation.

Bien à vous.

**Comment by Simperfit** [comment]
This is an english speaking repository.

@dunglas is not the only one working on the project, we are helping people using the framework on the symfony slack in the #api-platform channel.

I think in order to understand how to use, maybe is firstly to use it.

Thanks, I'm closing this one, as the issues are for bugfix or feature request on the distribution.
