### ISSUE TITLE
hashids support

### ISSUE THREAD

**Issue by vinyvicente** [api-platform/api-platform#724]
Hi everyone, has some strategy to convert primary keys of entities to hashids?

Example:
https://github.com/roukmoute/HashidsBundle
https://github.com/ivanakimov/hashids.php

If not, any idea to make this possible?

**Comment by teohhanhui** [comment]
You can just use https://github.com/ivanakimov/hashids.php directly. And implement a custom id generator: https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/reference/basic-mapping.html#identifier-generation-strategies

**Comment by teohhanhui** [comment]
The implementation could be very simple, similar to https://github.com/ramsey/uuid-doctrine/blob/1.4.3/src/UuidGenerator.php

**Comment by vinyvicente** [comment]
ok, @teohhanhui , but I won't change my integer ids, just I/O actions with hashids or uuid and translate to integer and persist internally. Make sense it?

**Comment by teohhanhui** [comment]
From the documentation: https://api-platform.com/docs/core/serialization/#entity-identifier-case

> ... the identifier must be marked explicitly using the `identifier` attribute of the `ApiPlatform\Core\Annotation\ApiProperty` annotation.

And you have a few options on how to convert between the hashid and the int id in the database. Will you be storing the hashid in the database as well?

**Comment by vinyvicente** [comment]
@teohhanhui not. I'll read just. Receive and transform and integer, or show as hashid. Internally is integer. It's best way because uuid increase the database size significantly. Is most like masked integer, to security, in this case :)

**Comment by teohhanhui** [comment]
Summoning @soyuka to help with the identifier black magic. :1st_place_medal:

**Comment by soyuka** [comment]
Just tell me if I understood correctly:

1. `GET /foo/{hash_id}`
2. do something with `{hash_id}` so that it becomes an `integer`
3. find the correct data in the database
4. return the resource but replace the id with the `{hash_id}`

If that's the case you need two things:

1. an [IdentifierDenormalizer](https://github.com/api-platform/core/blob/master/src/Bridge/RamseyUuid/Identifier/Normalizer/UuidNormalizer.php) that transforms the `{hash_id}` in an integer
2. a custom normalizer for properties marked as identifiers (use `PropertyMetadata->isIdentifier()`) and do the reverse transformation (`id` => `{hash_id}`) to keep the response identifiers as hashs instead of integers.

**Comment by vinyvicente** [comment]
@soyuka I'll try this. Keep issue to I show the result :)

Tks 4 support :+1:
