### ISSUE TITLE
Extremely slow DIC rebuild with api-platform enabled

### ISSUE THREAD

**Issue by tezvi** [api-platform/api-platform#838]
Hi guys,

I have around 50 API resource routes defined and when developing in symfony DEV environment DIC container is rebuilt on each request. The problem is that rebuild / compile takes up to 30 seconds. 
When inspecting profiler performance most of the time is being spent on SerializeListener. When I disable kernel debug mode the request usually takes 200-500 msecs, depending on SQL query complexity.

So far I tried mapping vendor and var/cache directory to tmpfs filesystem (ramdrive). Also I've tried tweaking php config (realpath caching etc.,) but no success. The only thing that helped was disabling xdebug extension completely, but that is a no go for development.
We're using Apache 2.4.x, and PHP 7.1 (FPM).

How could I optimize this so that my team developers can work normally and avoid frustration when you have to wait for half a minute after each small change in code?
Can someone point me to the right direction please.

**Comment by soyuka** [comment]
Hi,

I really don't have this issue, and my container is built only once. Because by default we use `metadata_cache` (https://github.com/api-platform/core/pull/1725) we only rebuild the cache manually when change resources. I'm also using experimental normalizer dumps (https://github.com/symfony/symfony/pull/22051) to improve the serialization speed but it doesn't look like it has something to do with the container...

I'll check but I don't think that I need/use xdebug.

**Comment by teohhanhui** [comment]
> The only thing that helped was disabling xdebug extension completely, but that is a no go for development.

We can't do anything about that. `xdebug` is known to have a major performance impact. If you really need to use it, you have to accept that performance penalty.

**Comment by tezvi** [comment]
Thanks for info. It seems that xdebug is most likely the bottleneck here. Developing without a debugger is another problem though.

**Comment by teohhanhui** [comment]
Not a debugger, but I just use `psysh` via https://github.com/theofidry/PsyshBundle
